steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/devconnector-server', '.' ]
  dir: 'server'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/devconnector-client', '.' ]
  dir: 'client'
  
images: ['eu.gcr.io/$PROJECT_ID/devconnector-server','eu.gcr.io/$PROJECT_ID/devconnector-client']
