apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: devcon-alexvak-com-tls
spec:
  secretName: devcon-alexvak-com
  issuerRef:
    name: devcon-letsencrypt-prod
    kind: ClusterIssuer
  commonName: devcon.alexvak.com
  dnsNames:
    - devcon.alexvak.com
    - www.devcon.alexvak.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - devcon.alexvak.com
          - www.devcon.alexvak.com
