apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: devcon-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "avakarchuk@me.com"
    privateKeySecretRef:
      name: devcon-letsencrypt-prod
    http01: {}
