apiVersion: apps/v1
kind: Deployment
metadata:
  name: devconnector-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: devconnector-server
  template:
    metadata:
      labels:
        component: devconnector-server
    spec:
      containers:
        - name: devconnector-server
          image: alexvak/devconnector-server
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: devconnector-secret
                  key: MONGO_URI
            - name: SECRET_OR_KEY
              valueFrom:
                secretKeyRef:
                  name: devconnector-secret
                  key: SECRET_OR_KEY
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
